name: fitness
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  sign_in_button: ^3.2.0
  google_fonts: ^4.0.4
  cloud_firestore: ^4.10.0
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/goal1.png
    - assets/images/runner.png
    - assets/images/eat-well.png
    - assets/images/meditate.png
    - assets/images/google-logo.png
    - assets/images/fitness-lady.png
    - assets/images/profile.png
    - assets/images/welcome-fitness.png
    - assets/images/home-bubble.png
    - assets/images/bmi-bg.png
    - assets/sleep/
    - assets/icons/
    - assets/images/meal.png